name: Terraform CI/CD

on:
  push:
    branches:
      - task_1
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1  # Modify as needed

jobs:
  terraform-check:
    name: Terraform Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.9.0'  # Specify the Terraform version

      - name: Terraform Format
        run: |
          terraform fmt -check
