name: List S3 Buckets

on:
  push:
    branches:
      - task_1  # Trigger on push to main branch, change as per your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  list-buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: List S3 Buckets
        run: aws s3api list-buckets --query 'Buckets[].Name' --output text
